#!/usr/local/bin/perl

use DBMS;
use Fcntl;
my $host= shift or 'localhost';

my $more_than_one = ($#ARGV==0) ? 0 : 1;

while(1) {
	last unless $ARGV[0]  =~ m/^-/;
	if ($1 eq '-l') {
		$more_than_one = 0;
		}
	else {
		@ARGV=(); 
		last;
		};
	};

if($#ARGV<0) {
	print STDERR "Syntax: $0 <dbms_host> [-l] <file [files]>\n";
	exit 1;
	};


foreach $file (@ARGV) {
	$file =~ s/\.([dbm]+)$//;
	tie %tmp, "DBMS",$file,O_RDONLY ,$host
		or die "Could not open $file: $! - $DBMS_ERROR";

	while(($k,$v)=each %tmp) {

		print $file." "
			if $more_than_one;

		print "$k =\t$v\n";
		};
	untie %tmp
	};

